dist: trusty
language: node_js
node_js:
  - "6"
before_install:
  - wget -O /tmp/firefox-unbranded.tar.bz2 http://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-release-linux64-add-on-devel/1493920526/firefox-53.0.2.en-US.linux-x86_64-add-on-devel.tar.bz2
  - tar xf /tmp/firefox-unbranded.tar.bz2 -C /tmp
  - wget -qO /tmp/chrome.zip https://download-chromium.appspot.com/dl/Linux_x64
  - unzip /tmp/chrome.zip -d /tmp
  - export PATH=/tmp/firefox:/tmp/chrome-linux:$PATH
  - "sed -i \"/travisBinary/{s=^.*\$=binary: '$(which chrome)',=}\" wdio.conf.js"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
